#!/bin/bash

# n c p f stands for new cpp problem file

read -p "Problem Name: " name
new_file_name="${name////$'-'}.cpp"
cpp_template_path="./templates/cpp_template.cpp";
js_template_path=""

if [ -f "$new_file_name" ]; then
    echo "Error, File is Already Exsist!"
    exit 1
fi

echo "Successfually -: File has been created"
echo
echo "File Problem Name: ${new_file_name}"
cp ${cpp_template_path} "${new_file_name}";
code "${new_file_name}";
